export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  RECTOR = 'RECTOR',
  COORDINATOR_ACADEMIC = 'COORDINATOR_ACADEMIC',
  COORDINATOR_CONVIVENCIA = 'COORDINATOR_CONVIVENCIA',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  GUARDIAN = 'GUARDIAN',
  SECRETARY = 'SECRETARY',
  ACCOUNTANT = 'ACCOUNTANT',
}
